create user mev030 identified by "oracle";
grant dba to mev030;


CREATE TABLE MEV030.TEST_TABLE AS SELECT * FROM DBA_OBJECTS;
CREATE INDEX MEV030.IDX_OBJECT_TYPE ON MEV030.TEST_TABLE (OBJECT_TYPE);
EXEC DBMS_STATS.GATHER_TABLE_STATS (ownname => 'MEV030', tabname => 'TEST_TABLE');
EXEC DBMS_STATS.GATHER_INDEX_STATS (ownname => 'MEV030', indname => 'IDX_OBJECT_TYPE');

